version: 2
jobs:

  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      SCRATCH: "/scratch"
      TEST_DATA_NAME: "circle-tests"
      TEST_DATA_URL: "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/590ce4a96c613b025147c568"
      MRIQC_API_TAG: 1.0.2

    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /tmp/src/mriqc
    steps:
      - run:
          name: Install parallel gzip and python3
          command: apk add --no-cache pigz python3
      - restore_cache:
          keys:
            - docker-v1-{{ .Branch }}-{{ epoch }}
            - docker-v1-{{ .Branch }}-
            - docker-v1-master-
            - docker-v1-
          paths:
            - /tmp/cache/docker.tar.gz

      - checkout
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
            fi
            if [ -f /tmp/cache/webapi.tar.gz ]; then
              pigz -d --stdout /tmp/cache/webapi.tar.gz | docker load
            fi
            docker images
      - run:
          name: Build Docker image
          no_output_timeout: 60m
          command: |
            # Inject MRIQC-WebAPI secret
            if [ "${MRIQC_API_SECRET_TOKEN}" != "" ]; then
              sed -i -E "s/<secret_token>/$MRIQC_API_SECRET_TOKEN/" mriqc/interfaces/webapi.py
              grep -q -i $MRIQC_API_SECRET_TOKEN mriqc/interfaces/webapi.py
            fi
            # Get version, update files.
            THISVERSION=$( python3 get_version.py )
            if [[ ${THISVERSION:0:1} == "0" ]] ; then
              echo "WARNING: latest git tag could not be found"
              echo "Please, make sure you fetch all tags from upstream with"
              echo "the command ``git fetch --tags --verbose`` and push"
              echo "them to your fork with ``git push origin --tags``"
            fi
            echo "${CIRCLE_TAG:-$THISVERSION}" > mriqc/VERSION
            # Build docker image
            e=1 && for i in {1..5}; do
              docker build \
                --cache-from=poldracklab/mriqc \
                --rm=false \
                -t poldracklab/mriqc:latest \
                --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                --build-arg VCS_REF=`git rev-parse --short HEAD` \
                --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save ubuntu:xenial-20161213 poldracklab/mriqc:latest \
              | pigz -2 -p 3 > /tmp/cache/docker.tar.gz
      - run:
          name: Prepare MRIQCWebAPI
          command: |
            pip3 install docker-compose
            rm -rf /tmp/src/mriqcwebapi
            cd /tmp/src && git clone https://github.com/poldracklab/mriqcwebapi.git && cd mriqcwebapi && git checkout ${MRIQC_API_TAG}
            if [ "${MRIQC_API_SECRET_TOKEN}" != "" ]; then
              sed -i -E "s/<secret_token>/$MRIQC_API_SECRET_TOKEN/" $HOME/mriqcwebapi/dockereve-master/.env
              grep -q -i $MRIQC_API_SECRET_TOKEN $HOME/mriqcwebapi/dockereve-master/.env
            fi
            docker-compose -f /tmp/src/mriqcwebapi/dockereve-master/docker-compose.yml pull
            docker-compose -f /tmp/src/mriqcwebapi/dockereve-master/docker-compose.yml build
      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save python:3.4-onbuild tutum/nginx:latest mongo:latest \
              | pigz -2 -p 3 > /tmp/cache/webapi.tar.gz
      - persist_to_workspace:
          root: /tmp
          paths:
            - cache/docker.tar.gz
            - cache/webapi.tar.gz
            - src/mriqc

  get_data:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /home/circleci/data
    steps:
      - restore_cache:
          keys:
            - data-v1-{{ epoch }}
            - data-v1-
      - run:
          name: Get test data
          command: |
            mkdir -p /tmp/data
            if [[ ! -d /tmp/data/${TEST_DATA_NAME} ]]; then
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O ${TEST_DATA_NAME}.tar.gz "${TEST_DATA_URL}"
              tar xvzf ${TEST_DATA_NAME}.tar.gz -C /tmp/data/
            else
              echo "Dataset ${TEST_DATA_NAME} was cached"
            fi
      - run:
          name: Create Nipype config files
          command: |
            mkdir -p /tmp/t1w
            printf "[execution]\nstop_on_first_crash = true\nremove_unnecessary_outputs = false\n" > /tmp/t1w/nipype.cfg
            echo "poll_sleep_duration = 0.2" >> /tmp/t1w/nipype.cfg
            echo "hash_method = content" >> /tmp/t1w/nipype.cfg
      - persist_to_workspace:
          root: /tmp
          paths:
            - data
            - t1w/nipype.cfg
      - save_cache:
         key: data-v1-{{ epoch }}
         paths:
            - /tmp/data
            - /tmp/t1w

  update_cache:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /tmp/src/mriqc
    steps:
      - attach_workspace:
          at: /tmp
      - save_cache:
         key: docker-v1-{{ .Branch }}-{{ epoch }}
         paths:
            - /tmp/cache/docker.tar.gz

  test_pytest:
    machine:
      image: circleci/classic:201711-01
    working_directory: /home/circleci/out/tests
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Run MRIQC tests
          no_output_timeout: 2h
          command: |
            docker run -ti --rm=false \
              -v $PWD:/scratch -w /usr/local/src/mriqc \
              --entrypoint="py.test" \
              poldracklab/mriqc:latest mriqc/ \
              --junitxml=/scratch/tests.xml \
              --doctest-modules --ignore=docs --ignore=src
      - store_test_results:
          path: /home/circleci/out/tests


  build_docs:
    machine:
      image: circleci/classic:201711-01
    working_directory: /home/circleci/out/docs
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Build MRIQC documentation
          no_output_timeout: 2h
          command: |
            docker run -ti --rm=false -v /home/circleci/out/docs:/scratch/docs \
              -w /usr/local/src/mriqc/docs \
              --entrypoint=sphinx-build poldracklab/mriqc:latest \
              -T -E -W -D language=en -b html source/ /scratch/docs 2>&1 \
              | tee $PWD/builddocs.log
            cat $PWD/builddocs.log
            grep -qv "ERROR" $PWD/builddocs.log
      - store_artifacts:
          path: /home/circleci/out/docs

  T1w:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/t1w
    environment:
      - MRIQC_API_HOST: $( hostname -I | awk '{print $1}' )

    steps:
      - attach_workspace:
          at: /tmp
      - restore_cache:
          keys:
            - t1w-anat-v1-{{ .Branch }}-{{ epoch }}
            - t1w-anat-v1-{{ .Branch }}
            - t1w-anat-v1-master
            - t1w-anat-v1-
            - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            sudo apt update && sudo apt -y install pigz
            if [ -f /tmp/cache/docker.tar.gz ]; then
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
            fi
            if [ -f /tmp/cache/webapi.tar.gz ]; then
              pigz -d --stdout /tmp/cache/webapi.tar.gz | docker load
            fi
            docker images
      - run:
          name: Start MRIQC WebAPI endpoint
          command: |
            nohup bash -c "docker-compose -f $HOME/mriqcwebapi/dockereve-master/docker-compose.yml --verbose up -d"
          background: true

      - run:
          name: Run participant-level on T1w images
          no_output_timeout: 2h
          command: |
            mkdir -p /tmp/t1w/work /tmp/t1w/derivatives
            sudo setfacl -d -m group:$(id -gn):rwx /tmp/t1w/derivatives
            sudo setfacl -m group:$(id -gn):rwx /tmp/t1w/derivatives
            sudo setfacl -d -m group:$(id -gn):rwx /tmp/t1w/work
            sudo setfacl -m group:$(id -gn):rwx /tmp/t1w/work
            # Run MRIQC
            docker run --rm=false -ti -v /tmp/data/${TEST_DATA_NAME}:/data:ro \
                       -v $PWD:/scratch -w /scratch \
                       poldracklab/mriqc:latest \
                       /data derivatives/ participant \
                       -vv --verbose-reports --profile -m T1w \
                       --n_procs 2 --ants-nthreads 1 --ants-float \
                       --webapi-url http://${MRIQC_API_HOST}/api/v1 --upload-strict"
      - save_cache:
         key: t1w-anat-v1-{{ .Branch }}-{{ epoch }}
         paths:
            - /tmp/t1w/work
            - /tmp/t1w/derivatives

      - run:
          name: Run group-level on T1w images
          no_output_timeout: 2h
          command: |
            docker run --rm=false -ti -v /tmp/data/${TEST_DATA_NAME}:/data:ro \
                       -v $PWD:/scratch -w /scratch \
                       poldracklab/mriqc:latest \
                       /data derivatives/ group \
                       -m T1w -vv

      - run:
          name: Checking changes on intermediate files of MRIQC
          command: |
            mkdir -p /tmp/t1w/test
            find /tmp/t1w/derivatives | sed s+/tmp/t1w/derivatives/++ | sort > /tmp/t1w/test/outputs.out
            diff /tmp/src/mriqc/.circleci/circle_T1w.txt /tmp/t1w/test/outputs.out
            exit $?

      - run:
          name: Checking changes on MD5 sums of intermediate files of MRIQC
          command: |
            mkdir -p /tmp/t1w/test
            export HASHCMD="docker run --rm=false -ti -v $PWD:/scratch \
                                       --entrypoint=/usr/local/miniconda/bin/nib-hash \
                                       poldracklab/mriqc:latest"
            find /tmp/t1w/derivatives -name "*.nii.gz" -type f  | sed s+/tmp/t1w/derivatives/++ | sort | xargs -n1 $HASHCMD >> /tmp/t1w/test/nii_outputs.txt
            diff /tmp/src/mriqc/.circleci/nii_T1w.txt /tmp/t1w/test/nii_outputs.out
            exit $?

      - run:
          name: Checking changes on IQMs
          command: |
            docker run --rm=false -ti -v $PWD:/scratch -w /scratch \
              --entrypoint="dfcheck" poldracklab/mriqc:latest \
              -i /scratch/derivatives/T1w.csv \
              -r /usr/local/src/mriqc/mriqc/data/testdata/T1w.csv
      - store_artifacts:
          path: /tmp/t1w/derivatives

  deploy:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/src/mriqc
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push poldracklab/mriqc:latest
              docker tag poldracklab/mriqc poldracklab/mriqc:$CIRCLE_TAG
              docker push poldracklab/mriqc:$CIRCLE_TAG
            fi
      - run:
          name: Deploy to PyPi
          command: |
            pip install "setuptools>=27.0" cython numpy twine future
            echo "${CIRCLE_TAG}" > mriqc/VERSION
            python setup.py sdist
            twine upload dist/*
            cd wrapper && python setup.py sdist
            twine upload dist/*

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - get_data:
          filters:
            branches:
              ignore: /docs?\/.*/
            tags:
              only: /.*/

      - build_docs:
          requires:
            - build
          filters:
            tags:
              only: /.*/

      - update_cache:
          requires:
            - build
          filters:
            branches:
              ignore: /docs?\/.*/
            tags:
              only: /.*/

      - test_pytest:
          requires:
            - build
          filters:
            branches:
              ignore: /docs?\/.*/
            tags:
              only: /.*/

      - T1w:
          requires:
            - get_data
            - build
          filters:
            branches:
              ignore: /docs?\/.*/
            tags:
              only: /.*/

      - bold:
          requires:
            - get_data
            - build
          filters:
            branches:
              ignore: /docs?\/.*/
            tags:
              only: /.*/

      - deploy:
          requires:
            - build
            - test_pytest
            - build_docs
            - T1w
            - bold
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
